### ISSUE TITLE
STT DEMO KWS -- "Drop down arrow" erroneously overlaps with full name of Arabic model in "drop down box"

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#1]
Hi Leonid, 

On STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, the user must select a model.
												
Issue: When selecting the “Modern Standard Arabic broadband model (16KHz)" in the "drop down box", the “drop down arrow” erroneously overlaps with the end part of the name, “ .... 16KHz”, because there is not enough room in the "drop down box" for this model name.

See attached spreadsheet for screen shots.

Please let me know if you have any questions or comments.

Alexandra

**Comment by Atreilly** [comment]
[STT DEMO KWS DEFECT-- Drop down arrow erroneously overlaps with full name of Arabic model in drop down box.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/131952/STT.DEMO.KWS.DEFECT--.Drop.down.arrow.erroneously.overlaps.with.full.name.of.Arabic.model.in.drop.down.box.xlsx)

**Comment by leonrch** [comment]
irrelevant
