### ISSUE TITLE
TTS DEMO EXPRESSIVE SSML -- Phoneme tag erroneously contains alphabelt instead of alphabet in SSML tab of voice language German Dieter and German Birgit

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#10]
HI Leonid, 

The user selects the voice language for German Dieter.
The user selects the SSML tab.
There is a phoneme tag in the text that erroneously contains "alphabelt" instead of "alphabet".

See attached spreadsheet for screen shots.

Alexandra
[TTS DEMO EXPRESSIVE SSML -- Phoneme tag erroneously contains alphabelt instead of alphabet in SSML tab of voice language German Dieter.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/138731/TTS.DEMO.EXPRESSIVE.SSML.--.Phoneme.tag.erroneously.contains.alphabelt.instead.of.alphabet.in.SSML.tab.of.voice.language.German.Dieter.xlsx)

**Comment by Atreilly** [comment]
Same issue (typo of "alphabelt") for voice language German Birgit.

I attached new spreadsheet for details of both German voice languages.

TTS DEMO EXPRESSIVE SSML -- Phoneme tag erroneously contains alphabelt instead of alphabet in SSML tab of voice language German Dieter and German Birgit

Alexandra

**Comment by leonrch** [comment]
Fixed. Please try it out.

**Comment by Atreilly** [comment]
Leonid, 

This works. Thank you.

I will close this issue now.

Alexandra
