### ISSUE TITLE
TTS DEMO EXPRESSIVE SSML -- For all non-English language voices, the non-English words in the Text Box of the  "Text" tab are erroneously underlined in red, after click in text box, or on DOWNLOAD or Speak buttons

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#12]
Leonid, 

TTS DEMO Expressive SSML ( https://text-to-speech-demo-lr.mybluemix.net/ ) -- For all non-English language voices, the non-English words in the Text Box of the  "Text" tab are erroneously underlined in red, after click in text box, or on DOWNLOAD or Speak buttons

The user selects any of the following non-English voice languages:

French (fr-FR): Renee (female)
German (de-DE): Birgit (female)
German (de-DE): Dieter (male)
Italian (it-IT): Francesca (female)
Japanese (ja-JP): Emi (female)
Brazilian Portuguese (pt-BR): Isabela (female)
Castilian Spanish (es-ES): Enrique (male)
Castilian Spanish (es-ES): Laura (female)
North American Spanish (es-US): Sofia (female)

The user either clicks in Text Box, on "Download" button, or "Speak" button. 
Note: Sometimes this doesn't happen on the first click, but after repeated clicks. Nonetheless, these red underlines are erroneous.

Some of all of the non-English words in the text box are erroneously underlined.
Perhaps these non-English words are checked against an English spell checker.

See attached spreadsheet for a few screen shots.

[TTS DEMO Expressive SSML DEFECT-- For all non-English language voices, the non-English words in the Text box of Text tab erroneously underlined in red, after click in text box or on DOWNLOAD or Speak buttons.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/138935/TTS.DEMO.Expressive.SSML.DEFECT--.For.all.non-English.language.voices.the.non-English.words.in.the.Text.box.of.Text.tab.erroneously.underlined.in.red.after.click.in.text.box.or.on.DOWNLOAD.or.Speak.buttons.xlsx)

Alexandra

**Comment by Atreilly** [comment]
[TTS DEMO Expressive SSML DEFECT-- For all non-English language voices, the non-English words in the Text box of Text tab erroneously underlined in red, after click in text box or on DOWNLOAD or Speak buttons.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/138958/TTS.DEMO.Expressive.SSML.DEFECT--.For.all.non-English.language.voices.the.non-English.words.in.the.Text.box.of.Text.tab.erroneously.underlined.in.red.after.click.in.text.box.or.on.DOWNLOAD.or.Speak.buttons.xlsx)

**Comment by Atreilly** [comment]
[TTS DEMO Expressive SSML DEFECT-- For all non-English language voices, the non-English words in the Text box of Text tab erroneously underlined in red.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/138961/TTS.DEMO.Expressive.SSML.DEFECT--.For.all.non-English.language.voices.the.non-English.words.in.the.Text.box.of.Text.tab.erroneously.underlined.in.red.xlsx)

**Comment by leonrch** [comment]
Fixed. Please try it out.

**Comment by Atreilly** [comment]
Leonid,

Thank you for fixing this. This works now!

I will close this issue now.

Alexandra
