### ISSUE TITLE
TTS DEMO EXPRESSIVE SSML -- Mispelled word "backordered" in text box in "Text" tab and "Expressive SSML" tab for "American English (en-US): Allison (female,expressive)" voice language

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#13]
TTS DEMO EXPRESSIVE SSML -- Mispelled word "backordered" in text box in "Text" tab and "Expressive SSML" tab for "American English (en-US): Allison (female,expressive)" voice language

Hi Leonid,

The user selects the voice language for American English (en-US): Allison (female,expressive)

The user selects the TEXT or SSML tab.
There is a word in the Text Box that is erroneously spelled as "backordered"; the correct spelling is "back-ordered".

In Text box:
"I have been assigned to handle your order status request. I am sorry to inform you that the items you requested are **backordered**. We apologize ... you a 50% discount!

Alexandra

**Comment by leonrch** [comment]
Fixed. Please try it out.

**Comment by Atreilly** [comment]
Leonid,

Thank you for fixing this. This works now!

I will close this issue now.

Alexandra
