### ISSUE TITLE
TTS DEMO EXPRESSIVE SSML-- Default audio player erroneously contains the audio from the previously selected TEXT or [Expressive] SSML tab for any selected voice language

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#14]
TTS DEMO EXPRESSIVE SSML-- Default audio player erroneously contains the audio from the previously selected TEXT or [Expressive] SSML tab for any selected voice language

Leonid,

I tested this using Chrome and Firefox and got the same results. 

Upon entry to the TTS Demo, the default audio player is empty (showing 0:00) for any selected voice language in either TEXT or SSML tab. However, default audio player is NOT empty (and showing time that is greater than 0:00) the next time the other (SSML or TEXT) tab is selected for the same selected voice language. The default audio player erroneously the contains the audio from the previously selected tab.

1 The user selects any voice language.
2 The user selects the "TEXT" tab.
3 The default audio player shows audio time of 0:00 for an empty file.
4 The user pressed the "Speak" button.
5 The default audio player shows audio time of non-zero, for the audio that was just created.
6 The user selects the other tab, "Expressive SSML", for same voice language.
7 The default audio player erroneously still shows audio time of non-zero, for the last audio that was just created for text in "TEXT" tab.
8 The user plays the audio via the default audio player and erroneously hears the previous text from TEXT tab, even though he/she just selected "Expressive SSML" or "SSML".

Note: This issue is related to issues 9 and 10.
https://github.com/leonrch/text-to-speech-nodejs/issues/9
https://github.com/leonrch/text-to-speech-nodejs/issues/10

Alexandra

**Comment by Atreilly** [comment]
Oops, I meant that this issue is related to the following issues (9 and 11 ... NOT 10):
https://github.com/leonrch/text-to-speech-nodejs/issues/9
https://github.com/leonrch/text-to-speech-nodejs/issues/11

**Comment by leonrch** [comment]
The default audio player gets hidden as soon as user changes tabs ('Text' <-> '[Expressive] SSML' or voices. The player will be shown again once its 'src' (source) property is set [to point to the latest audio file generated by the TTS service]. Therefore, the player DOESN'T contain the previous audio.
Please try it out.

**Comment by Atreilly** [comment]
Leonid,

This works. Thank you.

I will close this issue now.

Alexandra
