### ISSUE TITLE
STT DEMO KWS -- Keyword spotting box erroneously empty for all selected narrowband models for sample audios

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#2]
Hi Leonid,

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, the user must select a model.
																				When selecting any narrowband model listed below, no keywords are populated in the keyword spotting box, to use with either of the audio samples (“Play Sample 1”, “Play Sample 2”), as they are for all broadband models.								
[STT DEMO KWS DEFECT -- Keyword spotting box erroneously empty for all selected narrowband models for sample audios.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/131966/STT.DEMO.KWS.DEFECT.--.Keyword.spotting.box.erroneously.empty.for.all.selected.narrowband.models.for.sample.audios.xlsx)

	US English narrowband model (8KHz)								
	UK English narrowband model (8KHz)								
	Spanish narrowband model(8KHz)								
	Japanese narrowband model (8KHz)								
	Brazilian Portuguese narrowband model (8KHz)								
	Mandarin narrowband model (8KHz)								

See attached spreadsheet for screen shots and details.

Please let me know if you have any questions or comments.

Alexandra

**Comment by leonrch** [comment]
irrelevant
