### ISSUE TITLE
STT DEMO KWS -- FLAC audio file is not supported in Firefox, even though FLAC mentioned in "Transcribe Audio" section

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#3]
Leonid, 

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, the user selects a FLAC file, however receive message that no audio will accompany the transcription.

I uploaded a flac file (STT/english/broad/001.flac – I can't attach it below, but I will send it to you if needed), as per instructions in the  “Transcribe Audio” section, however, received a note that “browsers do not support playing FLAC audio, so no audio will accompany the transcription”.
	a) Why doesn't firefox support playing FLAC audio if it is mentioned in the “Transcribe Audio” section?	
	b) Why does message state the word “browsers” in plural? Right now we're only referring to one firefox brower. Shouldn't it say, “Notice: This browser does not support playing FLAC audio, so no audio will accompany the transcription.” and end with a period?	

See attached spreadsheet for screen shots and details.

Please let me know if you have any questions or comments.

Alexandra

**Comment by Atreilly** [comment]
[STT DEMO KWS DEFECT -- FLAC audio file is not supported in Firefox, even though Transcribe Audio section mentions it.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/131995/STT.DEMO.KWS.DEFECT.--.FLAC.audio.file.is.not.supported.in.Firefox.even.though.Transcribe.Audio.section.mentions.it.xlsx)

**Comment by leonrch** [comment]
irrelevant
