### ISSUE TITLE
STT DEMO KWS -- OPUS audio file is supported in Firefox, however OPUS excluded it from the “Transcribe Audio” section, where WAV and FLAC are mentioned	

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#4]
Hi Leonid, 

I uploaded a raw file 001.raw (note: I cannot attach it in this defect because file is not supported, however, I will send it to you, if needed), as per instructions in the  “Transcribe Audio” section, however, I received a message that “Only WAV or FLAC or Opus files can be transcribed, please try another file format”.								
	a) Why isn't the word “browser” used in the message, as it was in a message re: FLAC audios (like this ... “Notice: browers do not support playing FLAC audio, so no audio will accompany the transcription”)?								
	b) Why is OPUS excluded from the “Transcribe Audio” section, where WAV and FLAC are mentioned?								
	c) Why isn't “Opus” in the error message in capital letter like, “WAV” and “FLAC” are? Shouldn't it be “OPUS”								
	d) Why aren't the two complete sentences in the error message separated by a period or semicolon, instead of a comma?								

See attached spreadsheet for screen shots and details.

Please let me know if you have any questions or comments.

Alexandra

[STT DEMO KWS -- OPUS audio file is supported in Firefox, however OPUS excluded it from Transcribe Audio section, where WAV and FLAC are mentioned.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/131991/STT.DEMO.KWS.--.OPUS.audio.file.is.supported.in.Firefox.however.OPUS.excluded.it.from.Transcribe.Audio.section.where.WAV.and.FLAC.are.mentioned.xlsx)

**Comment by leonrch** [comment]
irrelevant
