### ISSUE TITLE
STT DEMO KWS -- Selected broadband model, but uploaded narrowband model and erroneously did NOT receive “Upsampling not allowed because recognition accuracy will suffer. Sampling rate of at least 16000 required.”

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#5]
Leonid, 

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, the user selects a broad model to upload, but actually uploads a narrowband file, however no error message was displayed. 

I uploaded a 002.opus US English narrowband audio file--I can't attached it here, but let me know if you need it), even though I selected “US English broad model (16KHz)” and did not receive the following expected error message:	
	“Upsampling not allowed because recognition accuracy will suffer. Sampling rate of at least 16000 required.”

See attached spreadsheet for screen shots and details.

[STT DEMO KWS DEFECT-- Selected broadband model but uploaded narrowband model and erroneously did NOT receive --Sampling rate of at least 16000 required.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/132004/STT.DEMO.KWS.DEFECT--.Selected.broadband.model.but.uploaded.narrowband.model.and.erroneously.did.NOT.receive.--Sampling.rate.of.at.least.16000.required.xlsx)

Please let me know if you have any questions or comments.

Alexandra

**Comment by leonrch** [comment]
irrelevant
