### ISSUE TITLE
STT DEMO KWS -- Selected non-English model, but uploaded English model and erroneously did NOT receive any type of message about the discrepancy between different language models

### ISSUE THREAD

**Issue by Atreilly** [leonrch/text-to-speech-nodejs#6]
Leonid, 

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, when the user selects a non-English model, but uploads English model, no error message is displayed. 

I uploaded a 002.wav US English narrowband audio file (note: I can't attach it here; please let me know if you need it), but selected “Japanese narrowband model (8KHz)” and did not receive any type of message about the discrepancy between different language models.

See attached spreadsheet for screen shots and details.

[STT DEMO KWS -- Selected non-English model, but uploaded English model and erroneously did NOT receive any type of message about the discrepancy between different language models.xlsx](https://github.com/leonrch/text-to-speech-nodejs/files/132016/STT.DEMO.KWS.--.Selected.non-English.model.but.uploaded.English.model.and.erroneously.did.NOT.receive.any.type.of.message.about.the.discrepancy.between.different.language.models.xlsx)

Please let me know if you have any questions or comments.

Alexandra

**Comment by leonrch** [comment]
irrelevant
